- name: Run Firewall
  hosts: localhost
  gather_facts: false
  roles:
    - delete_ssh_rule
    - add_ssh_rule
    
- name: Install Podman and run Nginx container
  hosts: all
  gather_facts: yes  # Replace with the name of your EC2 host or group
  remote_user: tfadmin  
  roles:
    - install_podman

  tasks:
    - name: Wait for 60 seconds
      wait_for:
        timeout: 60
    
- name: Install Podman and run Nginx container
  hosts: all
  gather_facts: yes  # Replace with the name of your EC2 host or group
  remote_user: tfadmin  
  roles:
    - delete_podman
